default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '\.(bat|cmd|ps1)$'
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: uv run --frozen ruff check --force-exclude
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: Ruff format
        entry: uv run --frozen ruff format --check --force-exclude
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy strict typing
        entry: uv run --frozen mypy
        language: system
        pass_filenames: false
        types_or: [python, pyi]
